language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t avinashnallam4441/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true avinashnallam4441/docker-react npm run test
